# Default values for prebid-pubsub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gcr.io/consumer-data-hub/rb_aide_frontend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#autoneg:
#  name:
#  max_rate_per_endpoint: 1000

service:
  type: NodePort
  port: 80
  containerPort: 80

ingress:
  enabled: true
  hosts:
    - host: gcp-aide-prd.rbone.net #domain name of app

  tls: []

cert:
  name: gcp-aide-prd-redirection-certificate #add cert name
  domainname: gcp-aide-prd.rbone.net #domain should be similar to ingress host

staticip:
  name: gcp-aide-prd-rbone-net-frontend-redirection #name of the static ip

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}

hpa:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60
