apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ default 1 .Values.hpa.minReplicas }}
  minReplicas: {{ default 1 .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name:  {{ .Chart.Name }}
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: {{ default 60 .Values.hpa.targetMemoryUtilizationPercentage }}
    type: Resource
  - resource:
      name: cpu
      targetAverageUtilization: {{ default 60 .Values.hpa.targetCPUUtilizationPercentage }}
    type: Resource
