apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
 name: {{ include "chart.fullname" . }}
 namespace: {{ .Values.namespace }}
spec:
 redirectToHttps:
   enabled: true
   responseCodeName: "301"